spring:
  datasource:
      url: jdbc:mysql://0.tcp.jp.ngrok.io:12000/sojuton
      driver-class-name: com.mysql.jdbc.Driver
      username: sojuton_user
      password: root!@

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.sojuton.*.model.dto
  configuration:
    map-underscore-to-camel-case: true