spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://10.10.4.183:33306/sojuton?serverTimezone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: sojuton_user
      password: root!@


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.sojuton.*.model.dto
  configuration:
    map-underscore-to-camel-case: true